import {NextResponse} from 'next/server'
const URL=process.env.NEXT_PUBLIC_SUPABASE_URL||'https://lkxvcphlrvaheccjraxm.supabase.co';const KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||''
function distance(a:number,b:number,c:number,d:number){const r=6371000,p=Math.PI/180,x=(c-a)*p,y=(d-b)*p,q=Math.sin(x/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin(y/2)**2;return 2*r*Math.asin(Math.sqrt(q))}
function lagosDate(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Lagos',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function lagosWeekday(){return new Intl.DateTimeFormat('en-US',{timeZone:'Africa/Lagos',weekday:'long'}).format(new Date())}
export async function POST(req:Request){try{
 const sr=await fetch(`${URL}/rest/v1/rpc/get_attendance_location`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${KEY}`,'Content-Type':'application/json'},body:'{}',cache:'no-store'});const locationRows=await sr.json();if(!sr.ok||!locationRows?.[0])return NextResponse.json({error:'Unable to read the current attendance configuration.'},{status:500});const config=locationRows[0]
 const configuredDays=Array.isArray(config.attendance_days)?config.attendance_days.map((x:string)=>x.toLowerCase()):['saturday'];const today=lagosWeekday();if(!configuredDays.includes(today.toLowerCase()))return NextResponse.json({error:`Attendance check-in is currently closed. Check-in is available on ${configuredDays.map((x:string)=>x.charAt(0).toUpperCase()+x.slice(1)).join(', ')}.`},{status:403})
 const{name,pin,lat,lng,accuracy}=await req.json();const cleanName=typeof name==='string'?name.trim().replace(/\s+/g,' '):'';if(!cleanName||typeof pin!=='string'||!/^\d{4}$/.test(pin))return NextResponse.json({error:'Enter your first or last name and 4-digit PIN.'},{status:400})
 // Identity is deliberately verified before any GPS/geofence rejection so a bad PIN never produces a misleading location error.
 const memberResponse=await fetch(`${URL}/rest/v1/rpc/check_choir_member`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${KEY}`,'Content-Type':'application/json'},body:JSON.stringify({p_name:cleanName,p_pin:pin}),cache:'no-store'});if(!memberResponse.ok)return NextResponse.json({error:'Attendance service is temporarily unavailable.'},{status:503});const members=await memberResponse.json(),member=Array.isArray(members)?members[0]:members;if(!member)return NextResponse.json({error:'Name or PIN is incorrect. Please try again.'},{status:401})
 if(typeof lat!=='number'||typeof lng!=='number'||!Number.isFinite(lat)||!Number.isFinite(lng))return NextResponse.json({error:'A valid location is required.'},{status:400})
 const s=config,churchLat=Number(s.church_latitude),churchLng=Number(s.church_longitude),radius=Number(s.church_radius_meters)||300;if(!Number.isFinite(churchLat)||!Number.isFinite(churchLng)||radius<=0)return NextResponse.json({error:'The super admin has not configured a valid attendance location yet.'},{status:500})
 const metres=distance(churchLat,churchLng,lat,lng)
 if(typeof accuracy==='number'&&Number.isFinite(accuracy)&&accuracy>100)return NextResponse.json({error:`GPS accuracy is ±${Math.round(accuracy)}m. Please move to an open area and wait for a more accurate location.` ,distanceMeters:Math.round(metres),accuracyMeters:Math.round(accuracy)},{status:403})
 if(metres>radius){const remaining=Math.max(1,Math.ceil(metres-radius));return NextResponse.json({error:`You are ${Math.round(metres)}m from ${String(s.church_name||'the selected attendance location')}. Move approximately ${remaining}m closer. You must be within ${radius}m to check in.`,distanceMeters:Math.round(metres),remainingMeters:remaining,radiusMeters:radius},{status:403})}
 const insert=await fetch(`${URL}/rest/v1/rpc/record_choir_attendance`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${KEY}`,'Content-Type':'application/json'},body:JSON.stringify({p_member_id:member.id,p_attendance_date:lagosDate(),p_lat:lat,p_lng:lng,p_accuracy:typeof accuracy==='number'?accuracy:null}),cache:'no-store'});if(!insert.ok)return NextResponse.json({error:'Unable to record attendance. Please try again.'},{status:503});const result=await insert.json();if(!result||!result.length)return NextResponse.json({error:'You have already checked in for today.'},{status:409});return NextResponse.json({ok:true,message:'Attendance recorded',member:{name:member.full_name},distanceMeters:Math.round(metres),checkedInAt:new Date().toISOString()})
}catch{return NextResponse.json({error:'Unable to process check-in.'},{status:500})}}