'use client'
import {useEffect,useState} from 'react'
import {LIFELINE_LOGO} from './lifeline-logo'
function lagosWeekday(){return new Intl.DateTimeFormat('en-US',{timeZone:'Africa/Lagos',weekday:'long'}).format(new Date())}
function dayName(v:string){return v.charAt(0).toUpperCase()+v.slice(1).toLowerCase()}
function distance(a:number,b:number,c:number,d:number){const r=6371000,p=Math.PI/180,x=(c-a)*p,y=(d-b)*p,q=Math.sin(x/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin(y/2)**2;return 2*r*Math.asin(Math.sqrt(q))}
export default function Home(){
 const[name,setName]=useState(''),[pin,setPin]=useState(''),[status,setStatus]=useState(''),[done,setDone]=useState(false),[loading,setLoading]=useState(false),[identityVerified,setIdentityVerified]=useState(false),[locationStatus,setLocationStatus]=useState('Location will be checked after your name and PIN are verified'),[distanceMeters,setDistanceMeters]=useState<number|null>(null),[venue,setVenue]=useState<any>(null),[attendanceDays,setAttendanceDays]=useState<string[]>(['Saturday']),[configLoading,setConfigLoading]=useState(true)
 const today=lagosWeekday(),isOpen=attendanceDays.map(x=>x.toLowerCase()).includes(today.toLowerCase()),dayText=attendanceDays.map(dayName).join(', ')
 useEffect(()=>{setConfigLoading(true);fetch('/api/location',{cache:'no-store'}).then(r=>r.json()).then(d=>{if(d.church_name){setVenue(d);if(Array.isArray(d.attendance_days)&&d.attendance_days.length)setAttendanceDays(d.attendance_days)}else setStatus(d.error||'Unable to load attendance configuration.')}).catch(()=>setStatus('Unable to load attendance configuration.')).finally(()=>setConfigLoading(false))},[])
 useEffect(()=>{setIdentityVerified(false);setDistanceMeters(null);setLocationStatus('Location will be checked after your name and PIN are verified')},[name,pin])
 async function verifyIdentity(){setStatus('');setLoading(true);try{const r=await fetch('/api/verify-member',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,pin})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Name or PIN is incorrect.');setIdentityVerified(true);setLocationStatus('Identity verified · getting your location…');return true}catch(e:any){setIdentityVerified(false);setStatus(e.message||'Unable to verify your name and PIN.');return false}finally{setLoading(false)}}
 async function requestLocation(){if(configLoading){setStatus('Loading attendance schedule…');return null}if(!isOpen){setStatus(`Check-in is currently closed. Available on ${dayText}.`);return null}if(!window.isSecureContext){setStatus('Location access requires a secure HTTPS connection.');return null}if(!navigator.geolocation){setStatus('This browser does not support location services.');return null}setLoading(true);setStatus('');setLocationStatus('Requesting your location…');try{const p=await new Promise<GeolocationPosition>((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,timeout:20000,maximumAge:0}));const d=venue?.church_latitude&&venue?.church_longitude?distance(Number(venue.church_latitude),Number(venue.church_longitude),p.coords.latitude,p.coords.longitude):null;if(d!==null){const rounded=Math.round(d);setDistanceMeters(rounded);const radius=Number(venue?.church_radius_meters)||300;setLocationStatus(rounded<=radius?`Location verified · ${rounded}m from attendance area · ±${Math.round(p.coords.accuracy)}m accuracy`:`You are ${rounded}m away · move approximately ${Math.max(1,Math.ceil(rounded-radius))}m closer · ±${Math.round(p.coords.accuracy)}m accuracy`)}else setLocationStatus(`Location ready · ±${Math.round(p.coords.accuracy)}m accuracy`);return p}catch(e:any){const c=e?.code;setLocationStatus(c===1?'Location permission denied':c===2?'Location unavailable':c===3?'Location request timed out':'Unable to access location');setStatus(c===1?'Allow Location for this website in your browser settings, then try again.':c===2?'Turn on Location Services and try again.':c===3?'Make sure Location Services are on and try again.':'Unable to access your location.');return null}finally{setLoading(false)}}
 async function checkIn(){setStatus('');setDistanceMeters(null);if(!identityVerified){const verified=await verifyIdentity();if(!verified)return}const p=await requestLocation();if(!p)return;setLoading(true);try{const r=await fetch('/api/check-in',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,pin,lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy})});const d=await r.json();if(d.distanceMeters!=null)setDistanceMeters(d.distanceMeters);if(!r.ok)throw new Error(d.error||'Check-in failed');setName(d.member?.name||name.trim());setDone(true)}catch(e:any){setStatus(e.message||'Unable to complete check-in.')}finally{setLoading(false)}}
 return <main className="member-page"><header className="member-header"><div className="member-brand"><img className="brand-logo-image" src={LIFELINE_LOGO} alt="Attendance logo"/><div><b>ATTENDANCE</b><span>Member Check-in</span></div></div><span className={`member-status ${!isOpen?'closed':''}`}>{configLoading?'LOADING':isOpen?'CHECK-IN OPEN':'CHECK-IN CLOSED'}</span></header><section className="member-main">{done?<div className="member-card success-card"><div className="success-icon">✓</div><span className="eyebrow">ATTENDANCE CONFIRMED</span><h1>You&apos;re marked present.</h1><p>{name} · Your attendance has been recorded successfully.</p><a className="member-button" href="/">BACK TO CHECK-IN</a></div>:<div className="member-card"><div className="member-intro"><span className="eyebrow">MEMBER CHECK-IN</span><h1>{configLoading?'Loading attendance schedule…':'Welcome back.'}</h1><p>{configLoading?'Please wait.':isOpen?'Enter your name and PIN first. We will verify your identity before requesting your location.':`Check-in is currently closed. Available on ${dayText}.`}</p></div>{venue&&<div className="venue-strip"><div className="venue-icon">⌖</div><div><b>ATTENDANCE LOCATION</b><span>Within {venue.church_radius_meters||300}m of the configured location</span></div><i>{isOpen?'ACTIVE':'CLOSED'}</i></div>}<div className="member-form"><div className="field"><label>NAME</label><input value={name} onChange={e=>setName(e.target.value)} placeholder="Enter your full name" autoComplete="name" disabled={loading||configLoading||!isOpen}/></div><div className="field"><label>4-DIGIT PIN</label><input className="pin" value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,'').slice(0,4))} inputMode="numeric" maxLength={4} placeholder="••••" disabled={loading||configLoading||!isOpen}/></div></div><div className="location-row"><span className="location-dot"/><span>{locationStatus}</span></div>{distanceMeters!==null&&venue&&<div className={`distance-panel ${distanceMeters<=Number(venue.church_radius_meters||300)?'inside':''}`}><strong>{distanceMeters}m</strong><span>{distanceMeters<=Number(venue.church_radius_meters||300)?'You are within the attendance area':`Move approximately ${Math.max(1,Math.ceil(distanceMeters-Number(venue.church_radius_meters||300)))}m closer`}</span></div>}{status&&<p className="member-error" role="alert">{status}</p>}<button className="member-button" disabled={loading||configLoading||!isOpen||!name.trim()||pin.length!==4} onClick={checkIn}>{loading?(identityVerified?'VERIFYING LOCATION…':'VERIFYING NAME & PIN…'):'CHECK IN'}</button><p className="privacy-note">Your location is used only to verify that you are within the configured attendance area.</p></div>}</section></main>
}
