<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

class Geo_Attend_Admin {
    public static function init() {
        add_action( 'admin_menu', array( __CLASS__, 'menu' ) );
        add_action( 'admin_post_geo_attend_save_settings', array( __CLASS__, 'save_settings' ) );
        add_action( 'admin_post_geo_attend_department', array( __CLASS__, 'department_action' ) );
        add_action( 'admin_post_geo_attend_member', array( __CLASS__, 'member_action' ) );
        add_action( 'admin_post_geo_attend_location', array( __CLASS__, 'location_action' ) );
        add_action( 'admin_post_geo_attend_export', array( __CLASS__, 'export_csv' ) );
        add_action( 'admin_enqueue_scripts', array( __CLASS__, 'assets' ) );
    }

    private static function cap() { return 'manage_options'; }
    private static function guard() { if ( ! current_user_can( self::cap() ) ) wp_die( esc_html__( 'You do not have permission to manage Geo-Attend.', 'geo-attend' ) ); }

    public static function menu() {
        add_menu_page( 'Geo-Attend', 'Geo-Attend', self::cap(), 'geo-attend', array( __CLASS__, 'dashboard' ), 'dashicons-location-alt', 58 );
        add_submenu_page( 'geo-attend', 'Dashboard', 'Dashboard', self::cap(), 'geo-attend', array( __CLASS__, 'dashboard' ) );
        add_submenu_page( 'geo-attend', 'Settings', 'Settings', self::cap(), 'geo-attend-settings', array( __CLASS__, 'settings_page' ) );
        add_submenu_page( 'geo-attend', 'Departments', 'Departments', self::cap(), 'geo-attend-departments', array( __CLASS__, 'departments_page' ) );
        add_submenu_page( 'geo-attend', 'Members', 'Members', self::cap(), 'geo-attend-members', array( __CLASS__, 'members_page' ) );
        add_submenu_page( 'geo-attend', 'Locations', 'Locations', self::cap(), 'geo-attend-locations', array( __CLASS__, 'locations_page' ) );
        add_submenu_page( 'geo-attend', 'Attendance', 'Attendance', self::cap(), 'geo-attend-attendance', array( __CLASS__, 'attendance_page' ) );
    }

    public static function assets( $hook ) {
        if ( false === strpos( $hook, 'geo-attend' ) ) return;
        wp_enqueue_style( 'geo-attend-admin', GEO_ATTEND_URL . 'assets/css/admin.css', array(), GEO_ATTEND_VERSION );
    }

    private static function header( $title, $subtitle = '' ) {
        echo '<div class="geo-admin-wrap"><div class="geo-admin-head"><div><span class="geo-admin-kicker">GEO-ATTEND</span><h1>' . esc_html( $title ) . '</h1>' . ( $subtitle ? '<p>' . esc_html( $subtitle ) . '</p>' : '' ) . '</div></div>';
        if ( isset( $_GET['geo_notice'] ) ) echo '<div class="notice notice-success is-dismissible"><p>' . esc_html( sanitize_text_field( wp_unslash( $_GET['geo_notice'] ) ) ) . '</p></div>';
    }
    private static function footer() { echo '</div>'; }

    public static function dashboard() {
        self::guard(); global $wpdb; $t=Geo_Attend_DB::tables(); $settings=Geo_Attend_DB::settings(); $date=isset($_GET['date'])?sanitize_text_field(wp_unslash($_GET['date'])):Geo_Attend_DB::now($settings['timezone'])->format('Y-m-d');
        $members=(int)$wpdb->get_var("SELECT COUNT(*) FROM {$t['members']} WHERE active=1");
        $present=(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$t['attendance']} WHERE attendance_date=%s",$date));
        $late=(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$t['attendance']} WHERE attendance_date=%s AND status='late'",$date));
        $departments=(int)$wpdb->get_var("SELECT COUNT(*) FROM {$t['departments']} WHERE active=1");
        self::header('Attendance dashboard','A configurable overview for your organization.');
        echo '<div class="geo-kpis"><div><span>Present</span><strong>'.esc_html($present).'</strong><small>'.esc_html($date).'</small></div><div><span>Late</span><strong>'.esc_html($late).'</strong><small>Marked late</small></div><div><span>Active members</span><strong>'.esc_html($members).'</strong><small>Member directory</small></div><div><span>Departments</span><strong>'.esc_html($departments).'</strong><small>Active categories</small></div></div>';
        echo '<div class="geo-panel"><div class="geo-panel-head"><div><h2>Attendance for '.esc_html($date).'</h2><p>Use the Attendance page for filtering and export.</p></div><a class="button button-primary" href="'.esc_url(admin_url('admin.php?page=geo-attend-attendance')).'">View attendance</a></div>';
        $rows=$wpdb->get_results($wpdb->prepare("SELECT a.*, CONCAT(m.first_name,' ',m.last_name) member_name, d.name department_name, l.name location_name FROM {$t['attendance']} a LEFT JOIN {$t['members']} m ON m.id=a.member_id LEFT JOIN {$t['departments']} d ON d.id=a.department_id LEFT JOIN {$t['locations']} l ON l.id=a.location_id WHERE a.attendance_date=%s ORDER BY a.checked_in_at DESC LIMIT 10",$date),ARRAY_A);
        self::table($rows,array('member_name'=>'Member','department_name'=>'Department','location_name'=>'Location','checked_in_at'=>'Checked in','status'=>'Status'));
        echo '</div>'; self::footer();
    }

    public static function settings_page() {
        self::guard(); $s=Geo_Attend_DB::settings(); self::header('Organization & attendance settings','Nothing in the attendance experience is tied to Lifeline or a specific organization.');
        echo '<form class="geo-panel geo-form" method="post" action="'.esc_url(admin_url('admin-post.php')).'">'; wp_nonce_field('geo_attend_settings'); echo '<input type="hidden" name="action" value="geo_attend_save_settings">';
        echo '<h2>Organization</h2><div class="geo-grid-2"><label>Organization / company name<input required name="organization_name" value="'.esc_attr($s['organization_name']).'"></label><label>Logo URL<input type="url" name="organization_logo" value="'.esc_attr($s['organization_logo']).'" placeholder="https://example.com/logo.png"></label></div>';
        echo '<h2>Attendance schedule</h2><div class="geo-days">'; foreach(array('Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday') as $day){echo '<label><input type="checkbox" name="attendance_days[]" value="'.esc_attr($day).'" '.checked(in_array($day,(array)$s['attendance_days'],true),true,false).'> '.esc_html($day).'</label>';} echo '</div>';
        echo '<div class="geo-grid-4"><label>Start time<input type="time" name="start_time" value="'.esc_attr($s['start_time']).'" required></label><label>End time<input type="time" name="end_time" value="'.esc_attr($s['end_time']).'" required></label><label>Late after (minutes)<input type="number" min="0" max="1440" name="late_after" value="'.esc_attr((int)$s['late_after']).'"></label><label>Max GPS accuracy (m)<input type="number" min="1" max="1000" name="max_accuracy" value="'.esc_attr((int)$s['max_accuracy']).'"></label></div>';
        echo '<div class="geo-grid-2"><label>Timezone<select name="timezone">'; foreach(DateTimeZone::listIdentifiers() as $tz){echo '<option value="'.esc_attr($tz).'" '.selected($s['timezone'],$tz,false).'>'.esc_html($tz).'</option>';} echo '</select></label><label class="geo-check"><input type="checkbox" name="allow_registration" value="1" '.checked(!empty($s['allow_registration']),true,false).'> Allow members to self-register</label></div>';
        echo '<p><button class="button button-primary button-large">Save settings</button></p></form>'; self::footer();
    }

    public static function save_settings(){self::guard();check_admin_referer('geo_attend_settings');$days=array_values(array_intersect(array('Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'),array_map('sanitize_text_field',(array)($_POST['attendance_days']??array()))));if(!$days) $days=array('Saturday');$start=sanitize_text_field(wp_unslash($_POST['start_time']??''));$end=sanitize_text_field(wp_unslash($_POST['end_time']??''));if(!preg_match('/^([01]\d|2[0-3]):[0-5]\d$/',$start)||!preg_match('/^([01]\d|2[0-3]):[0-5]\d$/',$end)||$start>=$end)wp_die('Invalid attendance time range.');$tz=sanitize_text_field(wp_unslash($_POST['timezone']??'UTC'));if(!in_array($tz,DateTimeZone::listIdentifiers(),true))$tz='UTC';$s=Geo_Attend_DB::settings();$s['organization_name']=sanitize_text_field(wp_unslash($_POST['organization_name']??''));$s['organization_logo']=esc_url_raw(wp_unslash($_POST['organization_logo']??''));$s['attendance_days']=$days;$s['start_time']=$start;$s['end_time']=$end;$s['late_after']=max(0,min(1440,absint($_POST['late_after']??0)));$s['max_accuracy']=max(1,min(1000,absint($_POST['max_accuracy']??100)));$s['timezone']=$tz;$s['allow_registration']=!empty($_POST['allow_registration']);update_option('geo_attend_settings',$s);wp_safe_redirect(add_query_arg(array('page'=>'geo-attend-settings','geo_notice'=>'Settings saved'),admin_url('admin.php')));exit;}

    public static function departments_page(){self::guard();global $wpdb;$t=Geo_Attend_DB::tables();if(isset($_GET['edit']))$edit=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$t['departments']} WHERE id=%d",absint($_GET['edit'])),ARRAY_A);else$edit=null;self::header('Departments / categories','Create the categories your organization uses.');echo '<div class="geo-panel"><h2>'.($edit?'Edit department':'Add department').'</h2><form class="geo-inline-form" method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('geo_attend_department');echo '<input type="hidden" name="action" value="geo_attend_department"><input type="hidden" name="id" value="'.esc_attr($edit['id']??0).'">';echo '<input required name="name" placeholder="e.g. Sales, Choir, Grade 10" value="'.esc_attr($edit['name']??'').'"><label><input type="checkbox" name="active" value="1" '.checked(!isset($edit['active'])||$edit['active'],true,false).'> Active</label><button class="button button-primary">Save</button></form></div>';$rows=$wpdb->get_results("SELECT d.*, (SELECT COUNT(*) FROM {$t['members']} m WHERE m.department_id=d.id AND m.active=1) member_count FROM {$t['departments']} d ORDER BY d.name",ARRAY_A);echo '<div class="geo-panel"><h2>Directory</h2>';self::table($rows,array('name'=>'Department','member_count'=>'Active members','active'=>'Status'),true,'geo-attend-departments');echo '</div>';self::footer();}

    public static function department_action(){self::guard();check_admin_referer('geo_attend_department');global $wpdb;$t=Geo_Attend_DB::tables();$id=absint($_POST['id']??0);$name=Geo_Attend_DB::normalize_name($_POST['name']??'');$active=!empty($_POST['active'])?1:0;if(!$name)wp_die('Department name is required.');$data=array('name'=>$name,'active'=>$active,'updated_at'=>current_time('mysql'));if($id)$wpdb->update($t['departments'],$data,array('id'=>$id),array('%s','%d','%s'),array('%d'));else{$data['created_at']=current_time('mysql');$wpdb->insert($t['departments'],$data,array('%s','%d','%s','%s'));}wp_safe_redirect(admin_url('admin.php?page=geo-attend-departments'));exit;}

    public static function members_page(){self::guard();global $wpdb;$t=Geo_Attend_DB::tables();$departments=$wpdb->get_results("SELECT id,name FROM {$t['departments']} WHERE active=1 ORDER BY name",ARRAY_A);$edit=null;if(isset($_GET['edit']))$edit=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$t['members']} WHERE id=%d",absint($_GET['edit'])),ARRAY_A);self::header('Members','Members use a 4-digit PIN for attendance. WordPress accounts are not required.');echo '<div class="geo-panel"><h2>'.($edit?'Edit member':'Add member').'</h2><form class="geo-form" method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="geo_attend_member">';wp_nonce_field('geo_attend_member');echo '<input type="hidden" name="id" value="'.esc_attr($edit['id']??0).'">';echo '<div class="geo-grid-2"><label>First name<input required name="first_name" value="'.esc_attr($edit['first_name']??'').'"></label><label>Last name<input required name="last_name" value="'.esc_attr($edit['last_name']??'').'"></label></div><div class="geo-grid-2"><label>Department<select name="department_id"><option value="0">Unassigned</option>';foreach($departments as $d)echo '<option value="'.esc_attr($d['id']).'" '.selected($edit['department_id']??0,$d['id'],false).'>'.esc_html($d['name']).'</option>';echo '</select></label><label>PIN '.($edit?'(leave blank to keep current)':'').'<input name="pin" inputmode="numeric" maxlength="4" pattern="\d{4}" '.($edit?'':'required').' placeholder="4 digits"></label></div><label class="geo-check"><input type="checkbox" name="active" value="1" '.checked(!isset($edit['active'])||$edit['active'],true,false).'> Active</label><p><button class="button button-primary">Save member</button></p></form></div>';
        echo '<div class="geo-panel"><div class="geo-panel-head"><div><h2>Member directory</h2><p>Export or manage the active directory.</p></div><a class="button" href="'.esc_url(wp_nonce_url(admin_url('admin-post.php?action=geo_attend_export&type=members'),'geo_attend_export')).'">Export CSV</a></div>'; $rows=$wpdb->get_results("SELECT m.*,d.name department_name FROM {$t['members']} m LEFT JOIN {$t['departments']} d ON d.id=m.department_id ORDER BY m.last_name,m.first_name",ARRAY_A);self::table($rows,array('first_name'=>'First name','last_name'=>'Last name','department_name'=>'Department','active'=>'Status'),true,'geo-attend-members');echo '</div>';self::footer();}

    public static function member_action(){self::guard();check_admin_referer('geo_attend_member');global $wpdb;$t=Geo_Attend_DB::tables();$id=absint($_POST['id']??0);$first=Geo_Attend_DB::normalize_name($_POST['first_name']??'');$last=Geo_Attend_DB::normalize_name($_POST['last_name']??'');$dept=absint($_POST['department_id']??0);$pin=preg_replace('/\D/','',(string)($_POST['pin']??''));if(!$first||!$last)wp_die('First and last name are required.');$data=array('first_name'=>$first,'last_name'=>$last,'department_id'=>$dept?:null,'active'=>!empty($_POST['active'])?1:0,'updated_at'=>current_time('mysql'));if(!$id&&!Geo_Attend_DB::pin_is_valid($pin))wp_die('PIN must be 4 different digits and cannot be a simple sequence.');if($pin)$data['pin_hash']=Geo_Attend_DB::hash_pin($pin);if($id)$wpdb->update($t['members'],$data,array('id'=>$id));else{$data['created_at']=current_time('mysql');$wpdb->insert($t['members'],$data);}wp_safe_redirect(admin_url('admin.php?page=geo-attend-members'));exit;}

    public static function locations_page(){self::guard();global $wpdb;$t=Geo_Attend_DB::tables();$edit=null;if(isset($_GET['edit']))$edit=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$t['locations']} WHERE id=%d",absint($_GET['edit'])),ARRAY_A);self::header('Attendance locations','Each location has its own GPS center and geofence radius.');echo '<div class="geo-panel"><h2>'.($edit?'Edit location':'Add location').'</h2><form class="geo-form" method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="geo_attend_location">';wp_nonce_field('geo_attend_location');echo '<input type="hidden" name="id" value="'.esc_attr($edit['id']??0).'">';echo '<div class="geo-grid-4"><label>Name<input required name="name" value="'.esc_attr($edit['name']??'').'" placeholder="Main office"></label><label>Latitude<input required type="number" step="0.0000001" name="latitude" value="'.esc_attr($edit['latitude']??'').'"></label><label>Longitude<input required type="number" step="0.0000001" name="longitude" value="'.esc_attr($edit['longitude']??'').'"></label><label>Radius (m)<input required type="number" min="10" max="10000" name="radius_meters" value="'.esc_attr($edit['radius_meters']??300).'"></label></div><label class="geo-check"><input type="checkbox" name="active" value="1" '.checked(!isset($edit['active'])||$edit['active'],true,false).'> Active</label><p><button class="button button-primary">Save location</button></p></form></div>';$rows=$wpdb->get_results("SELECT * FROM {$t['locations']} ORDER BY name",ARRAY_A);echo '<div class="geo-panel"><h2>Locations</h2>';self::table($rows,array('name'=>'Name','latitude'=>'Latitude','longitude'=>'Longitude','radius_meters'=>'Radius','active'=>'Status'),true,'geo-attend-locations');echo '</div>';self::footer();}

    public static function location_action(){self::guard();check_admin_referer('geo_attend_location');global $wpdb;$t=Geo_Attend_DB::tables();$id=absint($_POST['id']??0);$name=Geo_Attend_DB::normalize_name($_POST['name']??'');$lat=(float)($_POST['latitude']??0);$lng=(float)($_POST['longitude']??0);$radius=max(10,min(10000,(float)($_POST['radius_meters']??300)));if(!$name||$lat<-90||$lat>90||$lng<-180||$lng>180)wp_die('Enter a valid location.');$data=array('name'=>$name,'latitude'=>$lat,'longitude'=>$lng,'radius_meters'=>$radius,'active'=>!empty($_POST['active'])?1:0,'updated_at'=>current_time('mysql'));if($id)$wpdb->update($t['locations'],$data,array('id'=>$id));else{$data['created_at']=current_time('mysql');$wpdb->insert($t['locations'],$data);}wp_safe_redirect(admin_url('admin.php?page=geo-attend-locations'));exit;}

    public static function attendance_page(){self::guard();global $wpdb;$t=Geo_Attend_DB::tables();$date=sanitize_text_field(wp_unslash($_GET['date']??Geo_Attend_DB::now()->format('Y-m-d')));$dept=absint($_GET['department']??0);$departments=$wpdb->get_results("SELECT id,name FROM {$t['departments']} WHERE active=1 ORDER BY name",ARRAY_A);$where='a.attendance_date=%s';$args=array($date);if($dept){$where.=' AND a.department_id=%d';$args[]=$dept;}$rows=$wpdb->get_results($wpdb->prepare("SELECT a.*,CONCAT(m.first_name,' ',m.last_name) member_name,d.name department_name,l.name location_name FROM {$t['attendance']} a LEFT JOIN {$t['members']} m ON m.id=a.member_id LEFT JOIN {$t['departments']} d ON d.id=a.department_id LEFT JOIN {$t['locations']} l ON l.id=a.location_id WHERE $where ORDER BY a.checked_in_at DESC",$args),ARRAY_A);self::header('Attendance records','Filter by date and department, then export the result.');echo '<div class="geo-panel"><form class="geo-filters" method="get"><input type="hidden" name="page" value="geo-attend-attendance"><label>Date<input type="date" name="date" value="'.esc_attr($date).'" onchange="this.form.submit()"></label><label>Department<select name="department" onchange="this.form.submit()"><option value="0">All departments</option>';foreach($departments as $d)echo '<option value="'.esc_attr($d['id']).'" '.selected($dept,$d['id'],false).'>'.esc_html($d['name']).'</option>';echo '</select></label><a class="button" href="'.esc_url(wp_nonce_url(add_query_arg(array('action'=>'geo_attend_export','type'=>'attendance','date'=>$date,'department'=>$dept),admin_url('admin-post.php')),'geo_attend_export')).'">Export CSV</a></form>';self::table($rows,array('member_name'=>'Member','department_name'=>'Department','location_name'=>'Location','checked_in_at'=>'Checked in','accuracy'=>'GPS accuracy','status'=>'Status'),false);echo '</div>';self::footer();}

    public static function export_csv(){self::guard();check_admin_referer('geo_attend_export');global $wpdb;$t=Geo_Attend_DB::tables();$type=sanitize_key($_GET['type']??'attendance');if($type==='members'){$rows=$wpdb->get_results("SELECT m.id,m.first_name,m.last_name,d.name department,m.active FROM {$t['members']} m LEFT JOIN {$t['departments']} d ON d.id=m.department_id ORDER BY m.last_name,m.first_name",ARRAY_A);$filename='geo-attend-members.csv';}else{$date=sanitize_text_field(wp_unslash($_GET['date']??''));$dept=absint($_GET['department']??0);$where='1=1';$args=array();if($date){$where.=' AND a.attendance_date=%s';$args[]=$date;}if($dept){$where.=' AND a.department_id=%d';$args[]=$dept;}$rows=$wpdb->get_results($wpdb->prepare("SELECT a.attendance_date,a.checked_in_at,CONCAT(m.first_name,' ',m.last_name) member,d.name department,l.name location,a.latitude,a.longitude,a.accuracy,a.status FROM {$t['attendance']} a LEFT JOIN {$t['members']} m ON m.id=a.member_id LEFT JOIN {$t['departments']} d ON d.id=a.department_id LEFT JOIN {$t['locations']} l ON l.id=a.location_id WHERE $where ORDER BY a.checked_in_at DESC",$args),ARRAY_A);$filename='geo-attend-attendance.csv';}nocache_headers();header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename='.$filename);$out=fopen('php://output','w');if(!empty($rows))fputcsv($out,array_keys($rows[0]));foreach($rows as $row)fputcsv($out,$row);fclose($out);exit;}

    private static function table($rows,$columns,$actions=false,$page='') {if(!$rows){echo '<div class="geo-empty">No records found.</div>';return;}echo '<div class="geo-table-wrap"><table class="widefat fixed striped"><thead><tr>';foreach($columns as $key=>$label)echo '<th>'.esc_html($label).'</th>';if($actions)echo '<th>Actions</th>';echo '</tr></thead><tbody>';foreach($rows as $row){echo '<tr>';foreach($columns as $key=>$label){$value=$row[$key]??'';if($key==='active')$value=$value?'Active':'Inactive';if($key==='status')$value=ucfirst(str_replace('_',' ',$value));echo '<td>'.esc_html($value).'</td>';}if($actions){$id=absint($row['id']??0);$url=admin_url('admin.php?page='.$page.'&edit='.$id);echo '<td><a href="'.esc_url($url).'">Edit</a></td>';}echo '</tr>';}echo '</tbody></table></div>';}
}
